# Generated by Django 4.0.6 on 2022-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(default='https://st2.depositphotos.com/2586633/46477/v/380/depositphotos_464771766-stock-illustration-no-photo-or-blank-image.jpg', max_length=128),
        ),
    ]
