# Generated by Django 4.0.5 on 2022-07-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bid_bidder_bid_listing_bid_value_comment_commenter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_bids', to='auctions.listing'),
        ),
    ]
